#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyVox.Resource", IsApplication=true)]

namespace MyVox
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int angry = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int come = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dog = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int feel = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int give = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int go = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int goodbye = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int happy = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Hello = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int help = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int hi = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int home = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int hungry = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int I = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int love = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int play = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int please = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int potty = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ralph = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int run = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sleepy = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int thankyou = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int they = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int thirsty = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int word_button = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int you = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int I = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int angry = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int btnCamera = 2131099649;
			
			// aapt resource value: 0x7f06001a
			public const int come = 2131099674;
			
			// aapt resource value: 0x7f060007
			public const int custom = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int editText = 2131099657;
			
			// aapt resource value: 0x7f060017
			public const int feel = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int give = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int go = 2131099676;
			
			// aapt resource value: 0x7f06000d
			public const int goodbye = 2131099661;
			
			// aapt resource value: 0x7f060018
			public const int happy = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int helloMyNameIs = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int history = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int hungry = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int image_camera = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int myListView = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int niceToMeetYou = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int phrases = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int potty = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int ralph = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int speak = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int spokenHistoryList = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int thankYou = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int they = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int thirsty = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int tired = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int words = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int you = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_words = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int History = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int words = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int History = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int openCamera = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_style1 = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
